### ISSUE TITLE
Create a simple website for a book

### ISSUE THREAD

**Issue by Artazor** [Duck-commander/First#3]
Please take the following text: http://fan.lib.ru/s/shumil_p/text_0010-008.shtml

And create a set of web pages that will correspond to the chapters of the text.
There should be several types of pages:
1. Title Page (with illustration) on click should go to the contents page 
2. Contents page with a list of links to individual chapters
3. Set of chapter pages with navigation. Each chapter should have links to the previous and next chapter, as well to the contents page.

Each page should have a link to the original source (http://fan.lib.ru/s/shumil_p/text_0010-008.shtml)

For simplicity, you can use the `<pre>` tag when copying the text (read about that tag)

**Comment by Artazor** [comment]
Please reopen.

**Comment by Duck-commander** [comment]
Done. I created a new repository - Book
